title: ZBAR
description: writing, notes, fragments, and reviews
url: "https://zbar.blog"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: America/Denver
future: false

navigation:
  - title: home
    url: /
  - title: blog
    url: /blog/
  - title: reviews 
    url: /reviews/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: ZBAR





